
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Wed Feb 01 20:49:49 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INCREMENT = 26;
  public static final int CONST = 44;
  public static final int CHAR = 33;
  public static final int ASTERISK = 27;
  public static final int SLASH = 30;
  public static final int NOT_EQUAL = 16;
  public static final int CONTINUE = 42;
  public static final int LPAREN = 19;
  public static final int GREATER = 28;
  public static final int DECREMENT = 38;
  public static final int LESS = 21;
  public static final int MINUS = 15;
  public static final int RPAREN = 4;
  public static final int SEMICOLON = 6;
  public static final int AND = 18;
  public static final int OR = 43;
  public static final int BOOL = 8;
  public static final int COMMA = 5;
  public static final int CLASS = 37;
  public static final int LESS_EQUAL = 32;
  public static final int PLUS = 3;
  public static final int ASSIGN = 14;
  public static final int IF = 11;
  public static final int IS_EQUAL = 23;
  public static final int DOT = 12;
  public static final int EOF = 0;
  public static final int RETURN = 41;
  public static final int EQUAL = 20;
  public static final int GREATER_EQUAL = 31;
  public static final int NEW = 9;
  public static final int error = 1;
  public static final int PERCENT = 45;
  public static final int LCURLY = 13;
  public static final int NUMBER = 46;
  public static final int IDENT = 47;
  public static final int BREAK = 24;
  public static final int VOID = 17;
  public static final int RCURLY = 36;
  public static final int FOREACH = 35;
  public static final int COLON = 2;
  public static final int ELSE = 10;
  public static final int LSQUARE = 22;
  public static final int READ = 25;
  public static final int RSQUARE = 40;
  public static final int WHILE = 29;
  public static final int PROG = 39;
  public static final int EXTENDS = 7;
  public static final int PRINT = 34;
}

